name: Update README

on:
  schedule:
    - cron: '0 */6 * * *' # Atualiza a cada 6 horas
  workflow_dispatch: # Permite executar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update recent activity
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: '⚡ Atualiza atividade recente'
          MAX_LINES: 5
